### ISSUE TITLE
Basic connectivity test fail!

### ISSUE THREAD

**Issue by TAP96** [thotro/arduino-dw1000#102]
I used arduino uno with dwm1000 . i connected all pins correct but the result is like this
My question is why MISO is always HIGH(3.3V)? Please tell me what is wrong?
(I used BasicConnectivity Test)

Committed configuration ...
Device ID: DECA - model: 255, version: 15, revision: 15
Unique ID: FF:FF:FF:FF:FF:FF:FF:FF
Network ID & Device Address: PAN: FFFF, Short Address: FFFF

**Comment by pascalbros** [comment]
Can you shoot a photo of your configuration? We cannot help you if we don't know what you did.

**Comment by bendiken** [comment]
@TAP96 [How to ask questions the smart way](http://www.catb.org/esr/faqs/smart-questions.html#intro)

**Comment by Rotzbua** [comment]
@bendiken Thanks for this site, it is great :)
