### ISSUE TITLE
Issue with Basic Sender/Receiver Example

### ISSUE THREAD

**Issue by Nyuman** [thotro/arduino-dw1000#111]
Hi All,

I am trying to get the Basic Sender/Receiver Example working on my Arduino Uno Board. But the Arduino receives most of the time only one frame and then it stops or jumps back in the setup-function.
Had anyone the same problem and know how to solve it or what can cause such a behavior?

Data in Serial Monitor:
### DW1000-arduino-receiver-test ###
DW1000 initialized ...
Committed configuration ...
Device ID: DECA - model: 1, version: 3, revision: 0
Unique ID: FF:FF:FF:FF:00:00:00:00
Network ID & Device Address: PAN: 0A, Short Address: 06
Device mode: Data rate: 6800 kb/s, PRF: 64 MHz, Preamble: 1024 symbols (code #10), Channel:pÀþ### DW1000-arduino-receiver-test ###
DW1000 initialized ...
Committed configuration ...
Device ID: DECA - model: 1, version: 3, revision: 0
Unique ID: FF:FF:FF:FF:00:00:00:00
Network ID & Device Address: PAN: 0A, Short Address: 06
Device mode: Data rate: 6800 kb/s, PRF: 64 MHz, Preamble: 1024 symbols (code #10), Channel: #5
Received message ... #1
Data is ... ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FP power is [dBm] ... -92.88
RX power is [dBm] ... -50.52
Signal quality is ... 0.26
Received message ... #2
Data is ... Hello DW1000, it's #974
FP power is [dBm] ... -74.25
RX power is [dBm] ... -67.44
Signal quality is ... 119.66

**Comment by jmta** [comment]
I had this in the past and it was a bad ground connection that caused the issues
