### ISSUE TITLE
difference btw DW1000Ranging_TAG.ino and RangingTag.ino (resp DW1000Ranging_ANCHOR.ino and RangingAnchor.ino

### ISSUE THREAD

**Issue by wazaahhh** [thotro/arduino-dw1000#118]
I tried and used successfully both pairs of sketches to have 2 modules communicate together. However, RangingTag/Anchor.ino is way more precise than DW1000Ranging_TAG/ANCHOR. Yet the latter is made of much more streamlined code, and devices are uniquely identified, which is great.

Is there a reason for using one or another sketch pairs?

In both cases, anchors/tags are not super happy when I add a third device, either as anchor or tag. I gather from other issues that the code has not been written yet to accomplish  this task. I wonder if there is a to do list, which could help direct effort in this direction. Thanks.

**Comment by Rotzbua** [comment]
If I remember correctly:
Ranging was TOF.
DW1000Ranging was mod TOF from decawave, see data sheet.

**Comment by wazaahhh** [comment]
Thanks for the tip. I will investigate.

**Comment by DrummyFloyd** [comment]
hi any news about the difference between them ?
