### ISSUE TITLE
Library broken because of enableclock() in DW1000::begin()

### ISSUE THREAD

**Issue by ankitbhatia** [thotro/arduino-dw1000#12]
Hi,

This is something that needs to be fixed. The Enable clock function is trying to do SPI transfers before SPI begin. 

This can be solved by moving the enable clock call after SPI.begin() and SPI.usingInterrupts().

Regards,
Ankit

**Comment by thotro** [comment]
Hi Ankit,

oh, many thanks, will be fixed in the next commit!

Best,
Thomas
