### ISSUE TITLE
DW1000Ranging_ANCHOR / DW1000Ranging_TAG: delete inactive device: 1

### ISSUE THREAD

**Issue by sloubiou** [thotro/arduino-dw1000#122]
Hello everybody,

I'm using this great library from 1 month and ofen anchor or tag stop to send frames.
For exemple if Anchor stop, on TAG I have a "delete inactive device: 1".
Normaly there is on DW1000Ranging_ANCHOR a watchdog but only reset solve the issue.

Any idea?

Thanks and have a nice day

**Comment by Maxai2** [comment]
@sloubiou 
Hi! Can u tell me how u connect arduino to decawave?
