### ISSUE TITLE
Arduino Uno Diagram.

### ISSUE THREAD

**Issue by JakeJoo** [thotro/arduino-dw1000#123]
Hello, 

I try to using dwm1000 with arduino uno for check uwb location system.

But I don't know how can i connect pins to arduino Uno.

If someone have a diagram that connection with DWM1000. 

Could you upload to here please?

Thanks.

**Comment by curlyz** [comment]
I am a newbie but I cam across a  blog by daddy Wayne Holder , the lib was designed for ProMini , but he manage to used it with pro macro by changing some stuff , google it , it should work
