### ISSUE TITLE
Is it timestamp resolution is based on DWM oscillator ?

### ISSUE THREAD

**Issue by curlyz** [thotro/arduino-dw1000#134]
Hi, I am a little bit confused about timestamp.
My question is that 
When I use DW1000Time::setTimestamp , will this func write to the DWM the timestamp value that I want.
Or it just write this to arduino SRAM?
If this is possible,there should be a resetTimestamp func in DW1000Time
Thanks

**Comment by Slamoth** [comment]
Yes it is. Since 8 Mhz arduino pro mini can not really cope with 38.4 Mhz timestamping resolution.

**Comment by Rotzbua** [comment]
`DW1000Time` is an independent object. `DW1000Time::setTimestamp` sets the time of the object.
