### ISSUE TITLE
"Not found" in anchor example

### ISSUE THREAD

**Issue by yigibihe** [thotro/arduino-dw1000#138]
Hello, when I upload the anchor example I keep getting these messages. I uncommented the extra debug info from source.

`Not found
unknown: 8D:FE
Not found
unknown: 8D:FE
`
Digits change with almost every reboot.

**Comment by Rotzbua** [comment]
@yigibihe there are more than one anchor example, which is it?

**Comment by yigibihe** [comment]
"DW1000Ranging_ANCHOR" example.

**Comment by sarwadenj** [comment]
@yigibihe I'm too facing same problem,you get the data or not?

**Comment by Slamoth** [comment]
How many anchors and tags are you trying to make it work with ?

**Comment by hu265** [comment]
I got the same results from that example and I'm testing 1 tag with 1 anchor.

**Comment by khawajamechatronics** [comment]
I have same issue, working fine 1-1 communication but as soon as I add more tags or anchors. its give not found frequently

**Comment by hu265** [comment]
@khawajamechatronics Did you change anything on the code? What does your result look like for the 1-1 communication? Mine keeps on giving me "blink" and "delete inactive device".
