### ISSUE TITLE
API docs are empty

### ISSUE THREAD

**Issue by az-z** [thotro/arduino-dw1000#140]
Gents,
 it appears that [API html docs are empty](https://cdn.rawgit.com/thotro/arduino-dw1000/master/extras/doc/html/index.html). Is there a way to fix this?

**Comment by Rotzbua** [comment]
Doc is old, but not empty:
https://cdn.rawgit.com/thotro/arduino-dw1000/master/extras/doc/html/annotated.html

**Comment by az-z** [comment]
Sorry I thought api should refer to methods/functions and "data structures
"to data structures.
Does "old" means outdated=invalid? Or it (doc) is regenerate automatically
somehow?

**Comment by Rotzbua** [comment]
> Or it (doc) is regenerate automatically somehow?

no, no continues delivery available

> Does "old" means outdated=invalid?

old means (time) old... outdated for sure
` Generated on Sun Jul 12 2015 00:36:00 for Arduino driver library for Decawave DW1000 by   doxygen 1.8.6 `

**Comment by az-z** [comment]
Would you be interested to setup something like [this](http://rickfoosusa.blogspot.com/2011/10/howto-use-doxygen-with-github.html)
