### ISSUE TITLE
Using this code with TREK100 modules

### ISSUE THREAD

**Issue by savior-help** [thotro/arduino-dw1000#146]
hi
my question is can i use this code as tag along with decawave TREK1000 modules as anchors?
which configuration should i make or which example can i use.
i really appreciate your help.
thanks

**Comment by Rotzbua** [comment]
Seems to be similar to #61 .

**Comment by savior-help** [comment]
so what was the conclusion there????
i didn't see any certain answer there?
does this code support multi tags along with for example 4 anchors in general???

**Comment by Rotzbua** [comment]
Wow so much question marks. 

As you can read in the `readme`:
> A library that offers functionality to use Decawave's DW1000 chips/modules with Arduino 

Arduino != TREK100 ==> high chance that it will not work.

**Comment by savior-help** [comment]
Thanks

**Comment by cimbalo** [comment]
You can still disable TREK1000 ARM and connect the DW1000 chip to an Arduino using the TREK1000 SPI header (J6).

Please refer to the TREK1000 manual for the correct procedure.

**Comment by brettdaman** [comment]
Technically it should be possible, I also want to do this but even with the correct mode settings no ranging data is received.
