### ISSUE TITLE
In Basic Sender attachSentHandler() function not included in DW1000.h

### ISSUE THREAD

**Issue by sarwadenj** [thotro/arduino-dw1000#153]
I looked through the DW1000 class and header file but couldn't find attachSentHandler() function. Could let me know where this function is defined and what is does?

DW1000.attachSentHandler(handleSent);

**Comment by Rotzbua** [comment]
where: in header file

**Comment by sarwadenj** [comment]
Yes this function not defined in DW1000.h
It is called in Basic sender example.

**Comment by berkerbatur** [comment]
It is defined in DW1000.h, look at the latest source.

It lets you catch a new transmission event and perform accordingly.
See RangingAnchor & RangorTag in examples.

**Comment by sarwadenj** [comment]
@berkerbatur @Rotzbua Thanks..
