### ISSUE TITLE
Devide ID is ok, but what should be the Unique ID?

### ISSUE THREAD

**Issue by Mraeclo** [thotro/arduino-dw1000#157]
Hello how is it going?

Using the conectivity test example, I would like to know if getting a Unique ID: FF:FF:FF:FF:00:00:00:00 is a problem or if it should work

Device ID: DECA - model: 1, version: 3, revision: 0 is printing correctly.

thanks!

**Comment by sarwadenj** [comment]
@thotro I'm too getting Unique ID: FF:FF:FF:FF:00:00:00:00. 
What should be the Unique ID.

Thanks.

**Comment by Rotzbua** [comment]
It's ok

**Comment by VVHack** [comment]
It is really weird for me, I get a proper unique id whenever I apply 3.3 V and only FF:FF:FF:FF:00:00:00:00 when applying 5V.  Also, TX/RX does not work when I apply 3.3V
