### ISSUE TITLE
DMW1000 and NodeMCU Lolin

### ISSUE THREAD

**Issue by ferauche** [thotro/arduino-dw1000#171]
Does anyone had already tried to use NodeMCU ESP8266 connected to DMW1000?

NodeMCU ESP8266 (http://www.nodemcu.com/index_en.html#fr_54747361d775ef1a3600000f)

**Comment by CornevanDijk** [comment]
I am just buying the goods for the test

**Comment by CornevanDijk** [comment]
I hope to connecting the devices on friday 2017-03-10

**Comment by ferauche** [comment]
Any results from the NodeMCU connection?

**Comment by sarwadenj** [comment]
have a look...
https://github.com/vortex314/esp_tcp

 He was able to communicate with the DWM1000, but not very reliable.

**Comment by Rotzbua** [comment]
@CornevanDijk Did you got some results with the nodemcu?

**Comment by Rotzbua** [comment]
Seems working with esp #156 so nodemcu should work too.
