### ISSUE TITLE
Rotating tag changes the measurement

### ISSUE THREAD

**Issue by reycreator17** [thotro/arduino-dw1000#194]
Hi everyone. I'm using dwm1000_Tag and _anchor. 1 anchor and 1 tag connected.

 I just want to ask, why is it that when I rotate either the anchor or tag, the measurement of my serial monitor (of my tag) changes about +- 50 cm?

Is it some sort of normal or am I the only one having this?

Thanks 

Rey

**Comment by christoshadjiaslanis** [comment]
this is normal. The antenna is not isotropic. If the antennas are facing each other perfectly the most accurate and consistent ranging should be achieved.

**Comment by reycreator17** [comment]
So much thanks @christoshadjiaslanis 

BTW, what does the 16384 in the `writeValueToBytes(antennaDelayBytes, 16384, LEN_STAMP);` really mean?

Should each anchor and tag have different values of them to calibrate the precision?

**Comment by Rotzbua** [comment]
@reycreator17 Do not mix topics in issues.
