### ISSUE TITLE
Localisation according to triangulation/trilateration 

### ISSUE THREAD

**Issue by wangwangguoguo** [thotro/arduino-dw1000#200]
Anyone capable to localiser the tag? 
I havn't because the 3 distances don't arrive at the same time. How to solve this problem?

**Comment by Rotzbua** [comment]
Please use the template next time. Thanks.
https://github.com/thotro/arduino-dw1000/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by werty37** [comment]
@wangwangguoguo Follow the instructions here. I have been able to trilaterate using lemmingapex library.
https://github.com/lemmingapex/trilateration/issues/16#issuecomment-345462859
