### ISSUE TITLE
basic sender and receiver problem 

### ISSUE THREAD

**Issue by prvn194** [thotro/arduino-dw1000#207]
I AM USING WAYNE HOLDER ADAPTERBOARD FOR DWM 1000 WITH ARDUINO PRO MINI USING ARUINO IDE 1.6.8
I AM NOT ABLE TO FIGURE OUT HOW TO USE THE BASIC SENDER AND RECEIVER CODE,IT GETS UPLOADED BUT WHILE RUNNING IT 
### DW1000-arduino-sender-test ###
DW1000 initialized ...
Committed configuration ...
Device ID: FFFF - model: 255, version: 15, revision: 15
Unique ID: FF:FF:FF:FF:FF:FF:FF:FF
Network ID & Device Address: PAN: FFFF, Short Address: FFFF
Device mode: Data rate: 110 kb/s, PRF: 16 MHz, Preamble: 2048 symbols (code #4), Channel: #5
Transmitting packet ... #0
THIS IS WHAT I M GETTING AND NOMESSAGE AFTER THIS 
WHAT SHOULD I DO?

**Comment by Rotzbua** [comment]
This is questionable report. Closed.
