### ISSUE TITLE
attachInterrupt(digitalPinToInterrupt(_irq), DW1000Class::handleInterrupt, RISING); compiling error with STM32

### ISSUE THREAD

**Issue by AnhDongNguyen** [thotro/arduino-dw1000#208]
Hello I just want to upload the DW1000Ranging_ANCHOR example .ino project to STM32, but I got this error while compiling:

`attachInterrupt(digitalPinToInterrupt(_irq), DW1000Class::handleInterrupt, RISING); // todo interrupt for ESP8266
exit status 1
Error compiling for board Generic STM32F103C series.`

Please help me correct this

**Comment by curlyz** [comment]
Only AVR and maybe ESP is supported. Please read all the issue first and then realize that AVR is much simpler than ARM based.please close this issue

**Comment by Rotzbua** [comment]
@AnhDongNguyen You have to code it yourself. Best.
