### ISSUE TITLE
RANGING ERROR

### ISSUE THREAD

**Issue by prvn194** [thotro/arduino-dw1000#209]
@thotro 
I AM USING DWM 1000 WITH ARDUINO PRO MINI 5V
I AM HAVING PROBLEM WITH THE RANGE GIVEN BY DWM EVEN WHEN I AM PUTTING THEM VERY CLOSE TO EACH OTHER ,I AM HAVING 0.85 METRE AS RANGE .
AND I HAVE TESTED ON THE LARGE SCALE ALSO BUT I AM HAVING NON LINEAR ERROR THAT IS INCREASING WITH DISTANCE.

**Comment by Rotzbua** [comment]
Stop using caps lock. Stop spamming.
