### ISSUE TITLE
Connexion with only one anchor

### ISSUE THREAD

**Issue by Samoutcho** [thotro/arduino-dw1000#212]
Hi,

I work with Arduino IDE 1.8.3, with a localino board. I've no issue, the RangingAnchor/Tag softs work perfectly.

I looked for my problem on the wiki to find a clear response but i didn't find it, but i hope that i didn't miss it. 

I'm afraid about the programm will freeze if 10 anchors surrond my tag. Because it will try to get the distance of all the anchors.

Is there an easy way to just connect the tag with one anchor and keep only its distance from it ?

I think i need to change something in the DW1000ranging.cpp and the Networkdevicesnumber variable. 

But i'm a little bit loose in the programm.

Hope my post is in the right place and that's it's not a duplicate.

Have a good day.

Sam

**Comment by Rotzbua** [comment]
Freezing should be fixed with  #214.
