### ISSUE TITLE
Have someone successfully connect 1 tag with 4 anchors?

### ISSUE THREAD

**Issue by jack880019** [thotro/arduino-dw1000#218]
Hello! I am using this lib for indoor positioning project and now I can connect 1 tag with 3 anchors. And now I want to connect with 4 but it seems not working. Have someone successfully connect 1 tag with 4 anchors? I using the example code DW1000Ranging_ANCHOR. Plz give me some advise thx

**Comment by fatihpc** [comment]
Yeah. I wonder if this is the answer. Do you work with 4 anchors? Or more ...

**Comment by werty37** [comment]
I have a very basic question. Can you read the distance of a tag from all the anchors through only a single anchor?

**Comment by prideofisland** [comment]
> Have someone successfully connect 1 tag with 4 anchors? 

Hi @jack880019 
Of course, it is possible. I've tried it once, but never used it afterwards.
Check this line:
In DW1000Ranging.cpp
`//Max devices we put in the networkDevices array ! Each DW1000Device is 74 Bytes in SRAM memory for now.
#define MAX_DEVICES 4`

You have to increase this number. 

Piotr

**Comment by Rotzbua** [comment]
@pascalbros Thanks. I close this.
