### ISSUE TITLE
Connecting DWM 10000 with esp 8266 Lo-Lin

### ISSUE THREAD

**Issue by hdineth** [thotro/arduino-dw1000#220]
Hello,
I am working with an indoor localization project with DWM 1000 module. I need to know the method of connecting DWM 1000 with ESP 8266 module including
1. Pin connections
2. Code. (I use Arduino software to programme ESP 82666)

I tried to understand some community posts. But i cannot get it properly.
Thanks.

**Comment by Rotzbua** [comment]
Please use google or youtube to find tutorials to understand the ESP and Arduino IDE. Also you have to understand SPI and (Hardware)interrupts. Best.

**Comment by hdineth** [comment]
sir, i do know basics on esp8266 and arduino ide.i need to know on how to
connect esp8266 and dwm1000 via spi.

On Jul 21, 2017 4:15 PM, "Rotzbua" <notifications@github.com> wrote:

Please use google or youtube to find tutorials to understand the ESP and
Arduino IDE. Also you have to understand SPI and (Hardware)interrupts. Best.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thotro/arduino-dw1000/issues/220#issuecomment-316969841>,
or mute the thread

**Comment by curlyz** [comment]
Buy a dev kit from kuek, Localina. Nobody gonna help you with the ESP, try to understand that you must port it yourself to another MCU that is not supported by this project.

**Comment by werty37** [comment]
@hdineth I have been able to connect DWM1000 to Wemos D1 Mini. These are the pin mappings:

DWM1000 Adapter - ESP8266 WeMos D1

RST - D2
IRQ - D1
CLK - D5
MISO - D6
MOSI - D7
CS - D8

Hope this helps.

**Comment by ricgaldame** [comment]
Hello i am having the same issue with esp8266. Please somebody have a step by step about it?
