### ISSUE TITLE
The dw1000 trek1000 module doesnt respond anything, but a few times our module has sent some strange data. Could you please help me with connection? We have connected it through spi and used miso , mosi , irq , sck , ss(chip select) , ground and 3.3V power. Is this the right connection?

### ISSUE THREAD

**Issue by ThirtyOneDays** [thotro/arduino-dw1000#232]
### Step 1: What do you want?

* Report an issue.
* Improve code (and need help).
* Suggest a new feature.
* Present a new hardware adapter board or wiring.
* Want to report my experience or measurement. (Please also add them to the wiki!)

### Step 2: Describe your environment

 * Arduino IDE version or Toolchain: _____
 * dw1000 Library version: _____
 * Arduino device: _____
 * Used adapter board: _____
  
#### Affected file(s) or example(s):
  
  * Filename 1
  * Filename 2
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

```arduino
  // TODO(you): code here to reproduce the problem
```

**Comment by Rotzbua** [comment]
Spam.. sorry ..
