### ISSUE TITLE
DW1000 Configuration need help !

### ISSUE THREAD

**Issue by hle92294** [thotro/arduino-dw1000#234]
I hardly get ranging above 10 meter, and my currently used configuration are:
mode: MODE_LONGDATA_RANGE_ACCURACY
rate: TRX_RATE_110KBPS
frequency: TX_PULSE_FREQ_64MHZ
preamble length: TX_PREAMBLE_LEN_2048
DEFAULT_REPLY_DELAY_TIME :  3000 us
DEFAULT_TIMER_DELAY: 50

These are the things that i changed from the source, any help would be much appreciated

**Comment by Rotzbua** [comment]
@hle92294 Please use the template for issues https://github.com/thotro/arduino-dw1000/blob/master/.github/ISSUE_TEMPLATE.md . Thanks.
Please reopen a new reworked issue. Closed due a lack of information (no information about used micro controller, used board, compiler, library version, what source used for ranging... ).
