### ISSUE TITLE
Sent Handler is not called after startTransmit()

### ISSUE THREAD

**Issue by athlan** [thotro/arduino-dw1000#24]
I have run example code BasicSender in Arduino Mega 2560 R3. The output from Serial Monitor is as follows:

```
### DW1000-arduino-sender-test ###
DW1000 initialized ...
Committed configuration ...
Device ID: DECA - model: 1, version: 3, revision: 0
Unique ID: EUI: 0:0:0:0:255, OUI: 255:255:255
Network ID & Device Address: PAN: 10, Short Address: 5
Device mode: Data rate: 110 kb/s, PRF: 16 MHz, Preamble: 2048 symbols (code #4), Channel: #5
Transmitting packet ... #0
```

Unfortunately, after sending packet, the callback is not fired, which causes, that sentAck is not set to true. Main loop is breaking every each iteration.

**Comment by MarioRuz** [comment]
Same problem and I still do not know the reason (it also happens with the ranging example). Try to disconnect and connect one of the arduinos, by doing this it worked to me. I am wondering if this problem is due to the limited current the 3.3 V output can provide. Cheers.

**Comment by leosayous21** [comment]
How do you supply your module ? I had the same problem before when i used the arduino 3.3v regulator …

**Comment by athlan** [comment]
Guys, thank you for quick response. I am supplying DWM1000 directly from Arduino's 3.3V output.

**Comment by athlan** [comment]
Guys, thank you for quick response. I am supplying DWM1000 directly from Arduino's 3.3V output. But Auduino is supplied from USB itself.

**Comment by thotro** [comment]
Hi there!

(From the datasheet) Arduino's internal regulator only produces max. 50mA which is not enough to drive the TX current peaks of around 140mA (from the datasheet) of DW1000. As far as I remember @leosayous21 has a post somewhere around here on using an external regulator and further his adapter board may be a good reference - see [here](https://github.com/thotro/arduino-dw1000/tree/master/adapterBoard/dwm1000%20arduino%20standalone). 

Please also note that logical high on your I/O pins is about 5V; too much for the DW1000.

Hope it helps!
Cheers!

**Comment by abencomo** [comment]
@thotro, I'm using Wayne's [adapter](https://sites.google.com/site/wayneholder/uwb-ranging-with-the-decawave-dwm1000---part-ii) so I'm supplying 5V.  However, when I connect it to an [USB "Power Bank" Charger](https://www.amazon.com/gp/product/B01G1XH46M/ref=ox_sc_sfl_title_9?ie=UTF8&psc=1&smid=A2KUZVNQ9LP7N9), it only draws 40mA.  How should I power the module so it can be supplied it with 140mA as you indicated above?

![img_1029](https://cloud.githubusercontent.com/assets/7515273/19951407/0a8ea5d6-a11b-11e6-81c5-6d3437608d7f.JPG)

**Comment by wholder** [comment]
Hi, this is Wayne.  40ma is about what I'd expect the Arduino to draw by
itself,  So, I'm guess there is something wrong on the DWM1000 PCB.  Check
the voltage on the two pins marked 3.3 volts near the right lower edge of
the board (with DWM1000 at the top.)  This will show if the 3.3 regulator
is working.

Wayne

**Comment by abencomo** [comment]
Hi Wayne, do you mean pin 6 or 7 highlighted below?

![dwm1000-connections](https://cloud.githubusercontent.com/assets/7515273/19954183/4609402c-a133-11e6-9133-e1c962585d1f.jpg)

**Comment by wholder** [comment]
No.  See attached.

Wayne
[image: Inline image 1]

**Comment by abencomo** [comment]
Wayne, your attachment didn't come through...

**Comment by wholder** [comment]
Try this link:


https://sites.google.com/site/wayneholder/uwb-ranging-with-the-decawave-dwm1000---part-ii/DWM1000.png

Wayne

**Comment by abencomo** [comment]
Wayne, I do get 3.3V on those two pins (see picture below).

![img_1034](https://cloud.githubusercontent.com/assets/7515273/19974018/4cbd5022-a1a4-11e6-9ba5-6d075fdb7c3e.JPG)

**Comment by wholder** [comment]
Ok.  That's good.  At least the 3.3 regulator is working.  My other guess
is that perhaps the DWM1000 module is not completely soldered to the PCB.
I had some trouble with soldering the castellations myself and had to
reflow some of the connections to get the module working.  Did you build
more than one module?  If so, perhaps you can compare voltage levels on the
different pins.

Wayne

**Comment by abencomo** [comment]
I built four(4) modules and all of them show 3.3V on those pins.  I'll try to reflow the connections again, but it is quite odd that all four are not working.  Did you have to make any code changes (set unique ids, channels, etc.)?

**Comment by wholder** [comment]
It's odd that all 4 units would fail to work.  Can you post a photo of one
of the assembled boards without the Arduino mini installed so I can see how
you installed the components?  Perhaps I can spot a clue that way.  I used
a version of the software here that was posted some time ago, so something
may have changed since then.  I'm currently swamped with other tasks, but I
intend to try the latest software when I have the time.  But, until then, I
can only speculate as to the cause of your problem.  I do know that several
others have successfully built modules using my PCB, so I'm fairly
confident of the design.

**Comment by abencomo** [comment]
1 and 2 were my first try.  Thanks Wayne for looking into this.

![all4](https://cloud.githubusercontent.com/assets/7515273/19995340/8e3238fa-a213-11e6-9cae-e7e8e257e356.JPG)
![1](https://cloud.githubusercontent.com/assets/7515273/19995338/8e2e11e4-a213-11e6-84f0-02ab5aca6c7a.JPG)
![2](https://cloud.githubusercontent.com/assets/7515273/19995339/8e2f3b50-a213-11e6-981f-6e069d2c19a1.JPG)
![3](https://cloud.githubusercontent.com/assets/7515273/19995342/8e341e18-a213-11e6-9eb8-b96905c77e15.JPG)
![4](https://cloud.githubusercontent.com/assets/7515273/19995341/8e32b12c-a213-11e6-8e5c-28d68700ec8b.JPG)

**Comment by wholder** [comment]
To my eye, everything looks OK.  Since you say all 4 boards exhibit the
same symptoms, I'm staring to think it must be a software issue.  Perhaps
something has changed in the github code since I got my boards working.
I'd offer to send you my code as a test but, at the moment, I'm traveling
and don't have access to it.

To debug it yourself, I suggest you start by seeing if you can get the
BasicConnectivityTest sketch working.  I don't recall the exact values it's
supposed to print out and can't check while traveling, but perhaps someone
else here can give you the info.

Also, just to make sure, you are using 5 volt, Arduino Pro Minis on all the
boards, right?

Wayne

**Comment by abencomo** [comment]
Yes, I'm using the 5V [Arduino Pro Mini](https://www.sparkfun.com/products/11113) as well as the [SparkFun Pro Micro](https://www.sparkfun.com/products/12640).  Both display the same result when run the BasicConnectivityTest sketch, as shown below.

Once you are back home, would you mind trying the latest code from Master on one of your working the modules.  If that doesn't work, then you were right and it's a software issue.  That will also means that the version of the code that you have it's gold!

<img width="589" alt="screen shot 2016-11-02 at 9 11 40 am" src="https://cloud.githubusercontent.com/assets/7515273/20026368/03743a20-a2b7-11e6-87ce-6ae5273a0a30.png">

**Comment by SATHYALAKSHMI123456** [comment]
hello my board working but it detect only 5 meters .how can i increase above 50m .
