### ISSUE TITLE
loosing the connectivity from the anchor which has lowest short address.

### ISSUE THREAD

**Issue by hdineth** [thotro/arduino-dw1000#241]
I am developing a system with 3 anchors and 1 tag. i have given static short addresses to 3 anchors as "1","2" and "3". When receiving the range measurements, i always getting only from 2 anchors(from "2"and  "3"). the anchor which has lowest short address ("1" in above example) never connects to the tag. But when i change it's short address to a higher value like 4 or 5 , it connects to the tag successfully. but number '2' anchor stops communicating with tag. I already made the changes by adding volatile conditions as mentioned in issue 179.Can anyone have an idea to resolve this?
@thotro @MikeS159  @valeros  @gautierhattenberger

**Comment by Rotzbua** [comment]
For better issues please use the template: https://github.com/thotro/arduino-dw1000/blob/master/.github/ISSUE_TEMPLATE.md
Thanks.
