### ISSUE TITLE
Send custom messages with DW1000 ranging 

### ISSUE THREAD

**Issue by mjansrud** [thotro/arduino-dw1000#242]
Hi.

I am am trying to create a system where the tag knows the distance between each anchor. With other words, anchors receives distances between each other and transmits the information to the tag with a "regular" message.

Is this possible with the current library? If not, what is the best way to create that functionality?

Thanks in advance,

**Comment by Rotzbua** [comment]
For better issues please use the template: https://github.com/thotro/arduino-dw1000/blob/master/.github/ISSUE_TEMPLATE.md
Thanks.
