### ISSUE TITLE
Network ID and Device Address Incorrect

### ISSUE THREAD

**Issue by Ritesh23** [thotro/arduino-dw1000#243]
I am trying to run the BasicConnectivityTest for the DWM1000 chip and I am getting the following output: 
![image](https://user-images.githubusercontent.com/20907885/33179292-cd9ab2fc-d060-11e7-8a7a-cc27eb9a40c6.png)

I am unsure why the PAN is 00 and the Short Address is FF, I have not changed anything from the code (apart from adding a Serial.println later towards the end of the code).

I have connected the chip to an Arduino Uno as follows (The pins connected in the image to the Pro mini are the same as i have connected to my Uno):

![image](https://user-images.githubusercontent.com/20907885/33179410-38099608-d061-11e7-8887-7321b83bb125.png)

At first I thought this may be to do with the fact Arduino pins give out 5v, however as I am getting the Device ID as DECA - model: 1, version: 3, revision: 3, I don't think this is the issue, although I may be wrong.

Please could someone advise me as to why this issue with the PAN and Short Address is occurring and how I may go about solving this?

Thank You!

**Comment by Rotzbua** [comment]
This report does not satisfy the minimum requirement. (no used library version, no used example, no ide version...)
Please make a new issue where you use the template!!! https://github.com/thotro/arduino-dw1000/blob/master/.github/ISSUE_TEMPLATE.md
Thanks.
