### ISSUE TITLE
 library copying error

### ISSUE THREAD

**Issue by Ruben-26** [thotro/arduino-dw1000#249]
hello, I downloaded the dwm1000 library and do not copy the examples that it brings, can someone tell me how to fix it?

**Comment by Ruben-26** [comment]
I downloaded the library dwm1000 and the examples do not compile
can someone tell me how to fix it?

**Comment by Ruben-26** [comment]
this is the error that appears when compiling :

Arduino:1.8.5 (Windows 10), Tarjeta:"ESP32 Dev Module, QIO, 80MHz, 4MB (32Mb), 115200, None"

In file included from C:\Users\Usuario\Documents\Arduino\libraries\DW1000-0.5.0\examples\BasicConnectivityTest\BasicConnectivityTest.ino:15:0:

C:\Users\Usuario\Documents\Arduino\libraries\DW1000\src/DW1000.h:249:24: fatal error: ../SPI/SPI.h: No such file or directory

compilation terminated.

Se encontraron múltiples librerías para "DW1000.h"
Usado: C:\Users\Usuario\Documents\Arduino\libraries\DW1000
 No usado: C:\Users\Usuario\Documents\Arduino\libraries\DW1000-0.5.0
 No usado: C:\Users\Usuario\Documents\Arduino\libraries\DW1000-0.4.0
 No usado: C:\Program Files (x86)\Arduino\libraries\DW1000-0.5.0
exit status 1
Error compilando para la tarjeta ESP32 Dev Module.

**Comment by werty37** [comment]
Hi Ruben,

I can confirm that this library works with ESP8266. ESP32 is untested i believe. Looking at your error it seems like you are missing the SPI.h include in the default Arduino installation. 

`#include <SPI.h>`

Reinstall maybe? 

Cheers
S

**Comment by Ruben-26** [comment]
Hi werty37,

I have already managed to avoid that error, apparently I had not cloned the repositories well.
Now I see this error only when I try to load some example of dwm1000 on an esp32 adafruit Feather plate. with arduino plates one or nano if I can or to sibir these examples, although I opt for this result that I do not know if it is the expected one, because I only have one dwm1000.

![error spi using interrup](https://user-images.githubusercontent.com/34162304/34377153-fc795444-eaef-11e7-9b50-90c0636c6815.png)

![lecturas del dwm](https://user-images.githubusercontent.com/34162304/34378539-8daa3f7c-eaf6-11e7-93ef-4aa4118d0007.png)

**Comment by Ruben-26** [comment]
![lecturs dwm1000 bus spi](https://user-images.githubusercontent.com/34162304/34378915-ae76f716-eaf8-11e7-8756-37fc13112e91.png)

**Comment by werty37** [comment]
I don't know if someone has been able to interface the DWM1000 with ESP32. As the error suggests, usingInterrupt() is unavailable for ESP devices. You might want to take a look at the DW1000.cpp to understand how ESP8266 is initialized and maybe port it to work with ESP32. 

``` cpp
#ifndef ESP8266
	SPI.usingInterrupt(digitalPinToInterrupt(irq)); // not every board support this, e.g. ESP8266
#endif
```

Here is a thread which explains how ESP32 works
https://github.com/espressif/arduino-esp32/issues/624#issuecomment-353519453
