### ISSUE TITLE
Multi Tag issue

### ISSUE THREAD

**Issue by enesoztrk** [thotro/arduino-dw1000#250]
* Arduino IDE version or Toolchain: 1.6.8
 * dw1000 Library version: latest
 * Arduino device: Pro mini

  

Hello everyone,
I have used RangingAnchor and RangngTag examples and I try to make 1 Anchor and 3 tags connection,we cannot get  fast and stable data from tags.I changed channels dynamically but data rate is so slow .I think tags lose a lot of time with  setting	static void setChannel(byte channel);  function.Do you have any suggestion for me to improve this issue?

Best Regards,

**Comment by Rotzbua** [comment]
closed because inactivity
