### ISSUE TITLE
Control the GPIOs on the DWM1000 Module

### ISSUE THREAD

**Issue by Feixl** [thotro/arduino-dw1000#251]
Hi, i want to contol the GPIOs on the DWM1000 Module. In the library I only found the following function:
`void DW1000Class::setGPIOMode(uint8_t msgp, uint8_t mode) {
	byte gpiomode[LEN_GPIO_MODE];
	memset(gpiomode, 0, LEN_GPIO_MODE);
	readBytes(GPIO_CTRL, GPIO_MODE_SUB, gpiomode, LEN_GPIO_MODE);
	for (char i = 0; i < 2; i++){
		setBit(gpiomode, LEN_GPIO_MODE, msgp + i, (mode >> i) & 1);
	}
	writeBytes(GPIO_CTRL, GPIO_MODE_SUB, gpiomode, LEN_GPIO_MODE);
} 
`
This function is only used to set the Mode of the GPIO(Input, Output), am I right?
But how can i enable a GPIO, when I set it as an output?
Thanks for your help!

**Comment by werty37** [comment]
Please check wiki:
https://github.com/thotro/arduino-dw1000/wiki/DW(M)1000-LED-Blink-Feature
