### ISSUE TITLE
Combining Ranging with message sending

### ISSUE THREAD

**Issue by Rhodes187** [thotro/arduino-dw1000#258]
Hello, 

I am trying to combine two of the example sketches (BasicSender & DW1000Ranging_TAG, BasicReeceiver & DW1000Ranging_ANCHOR) such that for example while performing ranging, a message can be sent from  the tag to the anchor if a push button connected to the Arduino is pressed. 

I am having trouble however at the receiving end. I would like to ask if anyone has tried anything similar. I will be posting my code for the tag once refined. 

Thanks

**Comment by Rotzbua** [comment]
the dw1000 is a normal network device, so you can send messages. you have to program it by your own.
