### ISSUE TITLE
Arduino Pinout Diagram

### ISSUE THREAD

**Issue by gsat2018** [thotro/arduino-dw1000#263]
Complete newbie here...does anyone have some basic tutorials on connecting the DWM1000 to a Arduino (Uno or Pro Mini)? Please and thank you.

**Comment by werty37** [comment]
Have a look here:

https://github.com/thotro/arduino-dw1000/wiki/Testbed-and-Adapter-board
https://github.com/thotro/arduino-dw1000/wiki/Get-Started

**Comment by kuek** [comment]
Hi,
in case you do not want to solder much, we have some Localino v1.3 arduino mini boards left which are prepared to work with DWM1000. let me know in case you want them

kuek from localino.net
