### ISSUE TITLE
Localino hardware and multi tag

### ISSUE THREAD

**Issue by everythingisfine** [thotro/arduino-dw1000#272]
Hi guys,

is there anyone here who also uses Localino hardware from www.localino.net?

I have been successfully using this awesome platform with Ardunio and STM32 and the STM32F1 what Localino supplied, but I wanted to ask you how to manage multi Tag?

Localino guys offer a binary firmware, that already can handle multi tag and that works quite well, but they do not offer multi tag code. The stuff is great, because you get a running system for only 250 EUR... and don't need any additional things.  

Does anyone here solved multi tag in the arduno firmware? The localino platform has much more flash memory, so we can add tons of code, which is much better than using an Atmel 328p (pro mini).

Anyone here interested?

**Comment by darshb34** [comment]
I am using their platform to implement localization in a warehouse environment with multiple tags. The total area to be covered is 30m * 30m.
