### ISSUE TITLE
DWM1001 upload problem (JTAG interface not configured)

### ISSUE THREAD

**Issue by C-monC** [thotro/arduino-dw1000#275]
### Step 1: What do you want?
* Need help

### Step 2: Describe your environment

 * Arduino IDE version or Toolchain: 1.85
 * dw1000 Library version: 0.50
 * Arduino device: Arduino Uno
 * External power supply for DWM module (3.3V)
 * Used adapter board: No
 * Using DWM1001 module
  
### Step 3: Describe the problem
The boards available to me after installing required nRF52 library:

![image](https://user-images.githubusercontent.com/17007879/42412605-b8c605e6-820f-11e8-999d-5c34d58b113b.png)

This is the wiring diagram I used, although I used an Arduino Uno and a DWM1001 module with the Ready pin on the DWM1001 treated as the IRQ pin on the dwm1000. I am using a logic converter for the CSn, CLK and other SPI pins (MOSI and MISO) only. The other pins are directly connected. As mentioned above, I am using an external power supply to power the DWM1001 module (3.3V source). 

![image](https://user-images.githubusercontent.com/17007879/42412645-80b3ac20-8210-11e8-9cf6-cfc57b77c6f4.png)

#### Affected file(s) or example(s):
  
  * BasicConnectivityTest.ino
  
#### Steps to reproduce:

  1. Connect the wires as indicated in the diagram above.
  2. Select the Arduino Primo board in Arduino IDE
  3. Attempt a flash with the code from the BasicConnectivityTest example
  
#### Observed Results:

  ```c++
Sketch uses 35224 bytes (9%) of program storage space. Maximum is 385024 bytes.
  Open On-Chip Debugger 0.10.0-00004-g0e78f263 (2017-02-20-13:07)
  Licensed under GNU GPL v2
  For bug reports, read
 	http://openocd.org/doc/doxygen/bugs.html
  Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
  cortex_m reset_config sysresetreq
adapter speed: 5000 kHz
  Error: unable to find CMSIS-DAP device
  Error: No Valid JTAG Interface Configured.
  Error: No Valid JTAG Interface Configured. 

```
  
#### Expected Results:

  * That it would successfully flash and start outputting.
  
#### Relevant Code:

```c++
#include <SPI.h>
#include <DW1000.h>

// connection pins
const uint8_t PIN_RST = 4; // reset pin
const uint8_t PIN_IRQ = 2; // irq pin
const uint8_t PIN_SS = SS; // spi select pin

void setup() {
  // DEBUG monitoring
  Serial.begin(9600);
  // initialize the driver
  DW1000.begin(PIN_IRQ, PIN_RST);
  DW1000.select(PIN_SS);
  Serial.println(F("DW1000 initialized ..."));
  // general configuration
  DW1000.newConfiguration();
  DW1000.setDeviceAddress(5);
  DW1000.setNetworkId(10);
  DW1000.commitConfiguration();
  Serial.println(F("Committed configuration ..."));
  // wait a bit
  delay(1000);
}

void loop() {
  // DEBUG chip info and registers pretty printed
  char msg[128];
  DW1000.getPrintableDeviceIdentifier(msg);
  Serial.print("Device ID: "); Serial.println(msg);
  DW1000.getPrintableExtendedUniqueIdentifier(msg);
  Serial.print("Unique ID: "); Serial.println(msg);
  DW1000.getPrintableNetworkIdAndShortAddress(msg);
  Serial.print("Network ID & Device Address: "); Serial.println(msg);
  DW1000.getPrintableDeviceMode(msg);
  Serial.print("Device mode: "); Serial.println(msg);
  // wait a bit
  delay(10000);
}

```

**Comment by Rotzbua** [comment]
> Error: No Valid JTAG Interface Configured. 

Seems you have not configured a interface to flash the software. This is not a problem of the library.

**Comment by C-monC** [comment]
It's more of a question than a problem with the library. Just wanted to know if someone can help.
