### ISSUE TITLE
No communication

### ISSUE THREAD

**Issue by shizaasif** [thotro/arduino-dw1000#279]
Hello

I'm working with two dwm1000 modules. by using thotro's library, i'm able to make them work with Arduino UNO. But only the basic connectivity test is working. I am not getting anything transmitted or received. the basic sender/receiver and ranging anchor/tag are not working too. Only device information is shown and nothing else.

for basic sender, the serial monitor shows (Transmitting packet..... #) and then nothing. Also nothing at the receiver end too.

Kindly help me out with this, what could be the possible problem?
I've a project deadline upon us.

Thankyou

**Comment by Rotzbua** [comment]
Issue template is not a joke: https://github.com/thotro/arduino-dw1000/blob/master/.github/ISSUE_TEMPLATE.md
