### ISSUE TITLE
DW1000Ranging_TAG doesn't respond anything

### ISSUE THREAD

**Issue by Li-JEN** [thotro/arduino-dw1000#317]
I successfully passed the Basicconnecttest, but when I execute DW1000Ranging_Tag.h 
It just responds  
![t](https://user-images.githubusercontent.com/66358821/83763815-b84e9e80-a6ab-11ea-95f8-def8b60abcb6.jpg)
I found lots of websites, but no one fixes this problem.
Can somebody help me?
Thanks a lot.

**Comment by mindThomas** [comment]
The `DW1000Ranging_TAG` example is not supposed to output anything in the terminal during operation.
Please check the terminal output of the `DW1000Ranging_ANCHOR` example.

**Comment by dmasloub** [comment]
Would you mind sharing your fix?
