### ISSUE TITLE
Variable naming collision on STM32 builds..

### ISSUE THREAD

**Issue by stuartaw** [thotro/arduino-dw1000#39]
The current arg definition for DW1000RangingClass::initCommunication:
static void initCommunication(unsigned int RST=DEFAULT_RST_PIN, unsigned int SS=DEFAULT_SPI_SS_PIN);
Collides with defines for SS used in the stm32 support for arduino.
Can I suggest they are renamed avoiding uppercase first letter?
For testing I used myRST, mySS instead of RST, SS.

**Comment by leosayous21** [comment]
Ok i will commit this ! thanks !
