### ISSUE TITLE
Ranging problem in 2D (multiple Anchors)

### ISSUE THREAD

**Issue by Pyro-Brad** [thotro/arduino-dw1000#50]
Hello everyone,

First of all, great work guys! It's a large library and it works pretty good!

But here is my problem. (I’m sorry)

I have one tag and three anchors. 
This is my set-up to measure in 2D:

![anker_tag opstelling](https://cloud.githubusercontent.com/assets/15835259/11179030/e520947e-8c50-11e5-8d96-4cbee800a0da.png)
(Distances are centimeters)

This is what happens:
![range_problem_short](https://cloud.githubusercontent.com/assets/15835259/11179057/1164e2f6-8c51-11e5-96af-d4a9c516c302.jpg)

Each time an anchor joints the network the distance changes.

I tried it with a larger distance:
![range_probleem](https://cloud.githubusercontent.com/assets/15835259/11179086/44d23580-8c51-11e5-9084-e1c22b291af3.jpg)

Same result. The difference is a little bit smaller.
After one sample the distance is stable, good sign I think?
But... The distances doesn’t agree with the physical distance. 

The distance offset could be calibrated but that is not the problem in this case I think.
Because the distance changes each time when there joints an anchor.
- Could it be the transmit power?
  (How do I change the transmit power in the library?)
- Could it be the transmit mode? 

When this problem could be solved I can calculate the position in 2D.
Next step is 3D by adding a fourth anchor. (Firmware is already complete for 2D and 3D)

Could anyone help me? 
Thank you in advance.

**Comment by Pyro-Brad** [comment]
Setup is on a wooden table:
![setup](https://cloud.githubusercontent.com/assets/15835259/11179542/68ae740c-8c54-11e5-9a46-c6f8c6d5c165.jpg)

All the UWB modules are placed vertically.
Antenna is vertically polarized and increases the free space around the module antenna.
![tag_anchors](https://cloud.githubusercontent.com/assets/15835259/11179711/9b31cfb8-8c55-11e5-8e1d-da8c1db1a8ba.jpg)

The Tag and Anchors are a little bit higher than the table.
Because of possible UWB reflections.

**Comment by Pyro-Brad** [comment]
What I already tried:
(14-11-2015 14:33 uur)
- Anchor position from two to four.
- Channel from 5 to 2. (Because it was already channel 5)
- Switch off my wifi from my laptop.
*Still no other result.*

(place for next update)
-
-

**Comment by dtysky** [comment]
Hi, i  did some tests too and get some problem...  
  
![1](https://cloud.githubusercontent.com/assets/7337763/11207882/d6d2b3c2-8d52-11e5-9378-545f8e616097.JPG)  

![2](https://cloud.githubusercontent.com/assets/7337763/11207881/d6d12dae-8d52-11e5-9332-e54bdc965af6.JPG)  
  
1. The power which supply for dw1000 is really important, good power can let it work better and bad power could make it never work. And different power could the longest distance of two dw1000.  

2. The gap of distances from different anchors to tag are very large, this is result of following test:
test:  

![3](https://cloud.githubusercontent.com/assets/7337763/11207884/d6da0302-8d52-11e5-9089-3bcdd76c8476.JPG)  

result:  

![4](https://cloud.githubusercontent.com/assets/7337763/11207883/d6d57940-8d52-11e5-9665-8e749e1f445f.png)

**Comment by Broeserl** [comment]
Hi everbody, 

I have the same problems as the two guys before me.

I am testing with 2 Anchors and 1 Tag.
![aufbau](https://cloud.githubusercontent.com/assets/19702086/15735585/37bd6302-289a-11e6-95c5-a898c2bb70eb.jpg)

When i start only Anchor 1 and the Tag are on. The distance deviation is okay for me, about +-20 cm.
![anchor_1](https://cloud.githubusercontent.com/assets/19702086/15735862/2240855c-289c-11e6-95a0-32fd2c641000.jpg)

Now I power Anchor 2 and the distance of Anchor 1 changes.... 
The distance of Anchor 2 is "bad"...
![anchor_2](https://cloud.githubusercontent.com/assets/19702086/15735872/3552072e-289c-11e6-9f88-b537005881b8.jpg)

But when I turn off Anchor 1. (The value shown by A1, is an old one and not true)
The distance of Anchor 2 is now pretty good!
![anchor_1_off](https://cloud.githubusercontent.com/assets/19702086/15735875/39398bb4-289c-11e6-8801-d56fe62ff9bc.jpg)


I'm using DW1000.MODE_SHORTDATA_FAST_ACCURACY and channel 2.
I have tried all available modes and channels. The combination I used works best for me.


Could anyone help me? 
Thank you in advance.

**Comment by maxicastle** [comment]
You Can Use This Document to understand your Problem.
[Application Note APS014 Antena Delay Calibration.pdf](https://github.com/thotro/arduino-dw1000/files/355389/Application.Note.APS014.Antena.Delay.Calibration.pdf)

**Comment by AliSiddiqui4** [comment]
@Pyro-Brad can you please post the link to the code of your anchor and tag here. I am using the library example and my tag doesn't add the 3rd tag. I have tried changing the MODE.

**Comment by Rotzbua** [comment]
closed in favour of  #181

**Comment by duonghuu123** [comment]
If the distance is close, the error will be large, if you expand the distance to about 5m, the result is quite accurate
