### ISSUE TITLE
Transmit power erro

### ISSUE THREAD

**Issue by Pyro-Brad** [thotro/arduino-dw1000#51]
Hello everyone,

There seems to be a problem wtih the transmit power.
I can't chagne the transmit power.

Simple setup:
Anchor -> Tag

I use the standard library.
Correct me if I'm wrong:
Default settings are: channel 5, smartpower OFF.

The uC comes here:
DW1000.cpp line 550.
" writeValueToBytes(txpower, 0x85858585L, LEN_TX_POWER); "

This is the code line where it should be flashed in the DWM1000 module:
"writeBytes(TX_POWER, NO_SUB, txpower, LEN_TX_POWER);"

At the Tag I see no difference by RX power. 

Could anyone help me please?

**Comment by ebps** [comment]
Hi Pyro-Brad could you contact me at info at ebps.nl ? I see no option on git to PM you.

**Comment by Pyro-Brad** [comment]
Ga ik nu doen ;) (Lekker in het Nederlands)

**Comment by ebps** [comment]
Hi pYRO-bRAD,

 

Heb je gemaild op 1228943gerrits zuyd.nl Weet niet zeker of je mijn mail hebt ontvangen.

 


Met vriendelijke groet,

Bas van Dorenmalen


 <http://www.ebps.nl/> EBP Software B.V.

T: 040-2429988   |   W:  <http://www.ebps.nl/> www.ebps.nl
EBP Software B.V.
Bedrijvenweg 1  |  5627 BW  |  Eindhoven  |  The Netherlands 

 

Van: Pyro-Brad [mailto:notifications@github.com] 
Verzonden: vrijdag 27 november 2015 15:44
Aan: thotro/arduino-dw1000
CC: Bas van Dorenmalen
Onderwerp: Re: [arduino-dw1000] Transmit power erro (#51)

 

Ga ik nu doen ;) (Lekker in het Nederlands)

**Comment by Pyro-Brad** [comment]
Ik heb een mail terug gestuurd

**Comment by Pyro-Brad** [comment]
Goedemorgen Bas,

Heb je mijn mail ontvangen?

Groeten,

Bert Gerrits

**Comment by ebps** [comment]
Hi Gerrit,
Ik heb je terug gemaild.

**Comment by Pyro-Brad** [comment]
U heeft een reactie. Sorry voor de late mail.
