### ISSUE TITLE
Ranging vs. DW1000Ranging_

### ISSUE THREAD

**Issue by ChrisDziurzik** [thotro/arduino-dw1000#53]
Hi,

i copy the "reference"-circuite and test them. The example DW1000Ranging_ works, the Ranging do not. What is the different between the two programs? 
And i am right in my assumption, that both programs would have to run on the same hardware? I use the MiniPro with 8MHz lite the reference and an 330ohm resistor.

**Comment by paulerolland** [comment]
@ChrisDziurzik Hi Chris, I adapted this library for the Teensy and I have a similar problem. Does your BasicSender and BasicReceiver work? Mine don't.

**Comment by EarthBreaker** [comment]
Hi there @paulerolland, I'm trying to figure out what is wrong with mine as well. For some reason, my BasicSender and BasicReceiver can't work as well. Did you managed to solve the problem?

**Comment by MikeS159** [comment]
I also have this issue as of  0340035

**Comment by Rotzbua** [comment]
think its outdated
