### ISSUE TITLE
Connect IRQ and RESET in dwm-1000 pin to Arduino Mega 2560

### ISSUE THREAD

**Issue by firdausidwiki** [thotro/arduino-dw1000#57]
I try to connect this dwm-1000 with Arduino Mega 2560. Aside from the SPI pin , which pin in Arduino Mega 2560 should connect to IRQ pin and Reset pin in dwm-1000 ? please help me, i'm researching this sensor for my final project, thanks before.

**Comment by ttaber** [comment]
Here is an example wiring diagram for the Mega 2560 which mirrors that of the example using the Pro Mini:
![dwm1000adapter_w_mega2560](https://cloud.githubusercontent.com/assets/6174906/12862780/d2cc2df2-cc23-11e5-8abf-f9dd19f2743c.png)

**Comment by firdausidwiki** [comment]
why the IRQ pin connects to pin 21 / SCL pin ?
can it be connected to the other pin ? because i use the SCL pin as well

**Comment by reycreator17** [comment]
Hi @firdausidwiki 

Did it worked using arduino mega?

**Comment by reycreator17** [comment]
@ttaber

Don't we need to use level shifter here since mega is running on 5V logic? 

Kinda new here so dont be harsh Thanks

**Comment by firdausidwiki** [comment]
@reycreator17 actually i just search for the easiest ways to use dwm1000, because it is used for my final project in college, so i use it with pro Mini, i just dont have many times to continue research with arduino mega :')
I used arduino mega just for the data parsing from the pro Mini, because i need bigger memories to flash the program, and it works out fine

yes, you have to use level shifter from 5V to 3V3 if you want to connect with dwm1000, a little help for your question to ttaber. CMIIW

**Comment by reycreator17** [comment]
can I see your schematics in fritzing. The DWM1000 --> pro mini --> mega and also the codes for each

**Comment by Rotzbua** [comment]
A level shifter is required for mega. 5V logic micro controller are highly not recommended.
