### ISSUE TITLE
BaseReceiver restarts when BaseSender starts.

### ISSUE THREAD

**Issue by Wertolet** [thotro/arduino-dw1000#66]
Hi.
Im upload BaseSender on one arduino, and BaseReceiver to another.
Im start receiver first. It out base device info and waits. (Also im write debug output each 1000 ms., and it works fine).
After what Im start sender. Sender works fine, but at moment Im start sender - reciver freezes, no debug info, no other output.
When Im shutdown the sender, reciver reboots. (I think, when sender is ON, receiver just reboots every moment).
Any ideas?
My device scheme:
![default](https://cloud.githubusercontent.com/assets/17311073/13137578/f45a32a2-d632-11e5-8e97-c39d4c37b2f7.jpg)
RST - dpin 4, SS - dpin 9.

**Comment by Rotzbua** [comment]
Closed, due too less information. (lib/comp. vers.)
