### ISSUE TITLE
Define IRQ as pin# and call digitalPinToInterrupt(IRQ) 

### ISSUE THREAD

**Issue by wholder** [thotro/arduino-dw1000#68]
To be clearer and possibly portable to more Arduino boards, this code in DW1000Class::begin(int irq, int rat):

  SPI.usingInterrupt(irq);

should call digitalPinToInterrupt(pin) to lookup the IRQ number, such as:

  SPI.usingInterrupt(digitalPinToInterrupt(irq));

and the "irq" value should become the pin number use for the IRQ signal.  In addition, ideally, this value should also be passed in from calls like:

  DW1000Ranging.initCommunication(9, 10);

in DW1000Ranging_TAG.ino, and other example files.  I think it would also be clearer if these values were first declared as #define values, such as:
# define DW1000_IRQ  2
# define DW1000_RST 9
# define DW1000_CS   10

And these defined names then used in cals like DW1000Ranging.initCommunication().

Just by 2 cents.

Wayne

**Comment by Rotzbua** [comment]
I think that is what I changed with #82 .
