### ISSUE TITLE
Error in definition of NANOSECOND ?

### ISSUE THREAD

**Issue by SadE54** [thotro/arduino-dw1000#7]
I think there s a problem with the definition of NANOSECOND. As a unsigned long it can t be inferior to 1 : static const unsigned long NANOSECONDS = 1e-3;

**Comment by thotro** [comment]
Hi there, oops, thanks for pointing out! Will fix it temporarily with a float. In one to two days there will be a dedicated timing and timestamp concept to overcome any precision problems that are inevitable with the single precision types.
