### ISSUE TITLE
Any issue if we use 2 different arduino running at different frequency 

### ISSUE THREAD

**Issue by tn0432** [thotro/arduino-dw1000#71]
Hi! 

Will we have any issue if we uses 2 different arduino? for example
First board: Use arduino Pro mini 3.3V with clock speed 8Mhz
Second board: Use arduino nano 5V with clock speed 16Mhz

I let these 2 boards do two-way ranging together by decawaves.

Thanks

**Comment by MikeS159** [comment]
As long as you use level shifting on the 5V nano, and you run the SPI clock at the same speed both ends, I don't see why you would have a problem.
