### ISSUE TITLE
[DW1000Ranging] TAG/ANCHOR address should not be random

### ISSUE THREAD

**Issue by greymfm** [thotro/arduino-dw1000#79]
It is difficult to identify anchors if their addresses are random. Especially, if there is no wired connection between them. 

There should be an option for a static address  ( DW1000RangingClass::startAsAnchor / startAsTag ).

**Comment by MikeS159** [comment]
This is on my list of things to do next week :)

**Comment by mic980000** [comment]
I've got this sorted! ha..haa...EASY!

**Comment by mic980000** [comment]
![0001](https://cloud.githubusercontent.com/assets/20799262/17604730/a6a6f198-6049-11e6-85ed-0322e2532efb.png)

**Comment by manomitbal** [comment]
Is there a method of administering static addresses/names to the anchor/tag as we flash the devices?

**Comment by curlyz** [comment]
have you made it yet Mike , we count on you a lot =))

**Comment by MikeS159** [comment]
Sorry for never replying, I stoped working on this project some time ago. In DW1000Ranging.cpp there are two functions `DW1000RangingClass::startAsTag` `void DW1000RangingClass::startAsAnchor`

In these the following code creates the address
`	randomSeed(analogRead(0));`
`	_currentShortAddress[0] = random(0, 256);`
`	_currentShortAddress[1] = random(0, 256);`

I simply changed the function to take the last two bytes of the long address `currentAddress` which is set when you start a tag or anchor.

**Comment by Rotzbua** [comment]
Changed by @gautierhattenberger . Thanks.
