### ISSUE TITLE
Cheap hardware

### ISSUE THREAD

**Issue by Jinxit** [thotro/arduino-dw1000#97]
Hello,

I'm wondering what kind of cheap hardware would support this library. For example, would the Adafruit Pro Trinket, Arduino Pro Mini or Teensy LC work?

**Comment by MikeS159** [comment]
It will definitely work with a Pro Mini, see the wiki page for a board layout.
https://github.com/thotro/arduino-dw1000/wiki/Testbed-and-Adapter-board

**Comment by Jinxit** [comment]
Thanks!
