### ISSUE TITLE
list of part for dwm1000 arduino standalone

### ISSUE THREAD

**Issue by cyryllo** [thotro/arduino-dw1000#99]
Hello

Where can I find a list of needed parts and a description of board  dwm1000 arduino standalone?

**Comment by MikeS159** [comment]
https://github.com/thotro/arduino-dw1000/wiki/Testbed-and-Adapter-board
There are schematics for getting a board for the DWM100 made in the [repository ](https://github.com/thotro/arduino-dw1000/tree/master/adapterBoard)too.

**Comment by cyryllo** [comment]
I search info (list od parts) about this board https://github.com/thotro/arduino-dw1000/tree/master/adapterBoard/dwm1000%20arduino%20standalone

**Comment by MikeS159** [comment]
That looks like a Pro Mini chip with the minimum components to make it work, and the DWM1000. Maybe @leosayous21 can confirm?

**Comment by cyryllo** [comment]
I found in schemat file on Eagle ;)
